name: Sincronizar e processar arquivos markdown do repo privado estudos para blog

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync_and_process:
    runs-on: ubuntu-latest

    steps:
    - name: Fazer checkout do repo público blog (destino)
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Fazer checkout do repo privado estudos (origem)
      uses: actions/checkout@v3
      with:
        repository: lfelipeee/estudos
        token: ${{ secrets.ACCESS_TOKEN }}
        path: repo-estudos

    - name: Copiar somente arquivos markdown da raiz do repo privado para blog/content/posts
      run: |
        mkdir -p content/posts
        find 'repo-estudos/6 - Full Notes' -type f -name '*.md' -exec cp {} content/posts/ \; || echo "Nenhum arquivo markdown encontrado"

    - name: Commit e push com mensagens originais do repo estudos por arquivo
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add content/posts/

        if git diff --cached --quiet; then
          echo "Nada a commitar"
          exit 0
        fi

        # Mensagem simples com data atual
        msg="$(date '+%Y-%m-%d %H:%M:%S')"
        
        echo "$msg"
        git commit -m "$msg"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
