name: Sync and Process Posts

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'  # Roda diariamente às 00:00 UTC
  workflow_dispatch:      # Permite execução manual

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Hugo Blog
        uses: actions/checkout@v4
        with:
          repository: lfelipeee/hugo-blog
          token: ${{ secrets.ACCESS_TOKEN }}
          path: blog

      - name: Checkout Estudos Repo
        uses: actions/checkout@v4
        with:
          repository: lfelipeee/estudos
          token: ${{ secrets.ACCESS_TOKEN }}
          path: estudos

      - name: Process Markdown Files
        run: |
          # Cria diretório de destino
          mkdir -p blog/content/posts/
          
          # Processa cada arquivo .md
          for file in estudos/*.md; do
            [ -f "$file" ] || continue  # Garante que é arquivo
            
            filename=$(basename "$file")
            title="${filename%.md}"

            # Extrai tags do início do arquivo e formata
            tags=$(grep -oP '^#\w+' "$file" | sed 's/#//g' | paste -sd "," - | sed 's/\([^,]*\)/"\1"/g')

            # Verifica se contém #draft
            draft=$(grep -q '#draft' "$file" && echo "true" || echo "false")

            # Remove todas as linhas de tags do corpo
            sed -i '/^#\w\+/d' "$file"

            # Obtém data do último commit ou usa data atual
            commit_date=$(git -C estudos log -1 --format="%cI" -- "$file" || true)
            commit_date=${commit_date:-$(date -u +"%Y-%m-%dT%H:%M:%SZ")}

            # Gera o conteúdo com front matter e corpo
            {
              echo "---"
              echo "title: \"$title\""
              echo "date: $commit_date"
              echo "tags: [$tags]"
              echo "draft: $draft"
              echo "---"
              cat "$file"
            } > "blog/content/posts/$filename"
          done

      - name: Commit and Push
        run: |
          cd blog
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add content/posts/
          
          if ! git diff --quiet; then
            git commit -m "Atualização automática de posts [$(date +'%Y-%m-%d %H:%M')]"
            git push
          else
            echo "Nenhuma alteração detectada"
          fi
